/*
 * This file is generated by jOOQ.
 */
package me.ryang.jooq.jooq_example;


import me.ryang.jooq.jooq_example.tables.Address;
import me.ryang.jooq.jooq_example.tables.Jobs;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in jooq_example.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADDRESS_PEOPLE_ID = Internal.createIndex(DSL.name("people_id"), Address.ADDRESS, new OrderField[] { Address.ADDRESS.PEOPLE_ID }, false);
    public static final Index JOBS_PEOPLE_ID = Internal.createIndex(DSL.name("people_id"), Jobs.JOBS, new OrderField[] { Jobs.JOBS.PEOPLE_ID }, false);
}
