/*
 * This file is generated by jOOQ.
 */
package me.ryang.jooq.jooq_example;


import java.util.Arrays;
import java.util.List;

import me.ryang.jooq.DefaultCatalog;
import me.ryang.jooq.jooq_example.tables.Address;
import me.ryang.jooq.jooq_example.tables.Jobs;
import me.ryang.jooq.jooq_example.tables.People;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqExample extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jooq_example</code>
     */
    public static final JooqExample JOOQ_EXAMPLE = new JooqExample();

    /**
     * The table <code>jooq_example.address</code>.
     */
    public final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>jooq_example.jobs</code>.
     */
    public final Jobs JOBS = Jobs.JOBS;

    /**
     * The table <code>jooq_example.people</code>.
     */
    public final People PEOPLE = People.PEOPLE;

    /**
     * No further instances allowed
     */
    private JooqExample() {
        super("jooq_example", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Address.ADDRESS,
            Jobs.JOBS,
            People.PEOPLE);
    }
}
