/*
 * This file is generated by jOOQ.
 */
package me.ryang.jooq.jooq_example;


import me.ryang.jooq.jooq_example.tables.Address;
import me.ryang.jooq.jooq_example.tables.Jobs;
import me.ryang.jooq.jooq_example.tables.People;
import me.ryang.jooq.jooq_example.tables.records.AddressRecord;
import me.ryang.jooq.jooq_example.tables.records.JobsRecord;
import me.ryang.jooq.jooq_example.tables.records.PeopleRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * jooq_example.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AddressRecord> KEY_ADDRESS_PRIMARY = Internal.createUniqueKey(Address.ADDRESS, DSL.name("KEY_address_PRIMARY"), new TableField[] { Address.ADDRESS.ID }, true);
    public static final UniqueKey<JobsRecord> KEY_JOBS_PRIMARY = Internal.createUniqueKey(Jobs.JOBS, DSL.name("KEY_jobs_PRIMARY"), new TableField[] { Jobs.JOBS.ID }, true);
    public static final UniqueKey<PeopleRecord> KEY_PEOPLE_PRIMARY = Internal.createUniqueKey(People.PEOPLE, DSL.name("KEY_people_PRIMARY"), new TableField[] { People.PEOPLE.ID }, true);
}
