/*
 * This file is generated by jOOQ.
 */
package me.ryang.jooq.jooq_example;


import me.ryang.jooq.jooq_example.tables.Address;
import me.ryang.jooq.jooq_example.tables.Jobs;
import me.ryang.jooq.jooq_example.tables.People;


/**
 * Convenience access to all tables in jooq_example.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq_example.address</code>.
     */
    public static final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>jooq_example.jobs</code>.
     */
    public static final Jobs JOBS = Jobs.JOBS;

    /**
     * The table <code>jooq_example.people</code>.
     */
    public static final People PEOPLE = People.PEOPLE;
}
