version: '3.3'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'jooq_example'
      MYSQL_USER: "${DB_USER}"
      # You can use whatever password you like
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "${ROOT_PASSWORD}"
    ports:
      - "${DB_PORT}:3306"
    expose:
      - "${DB_PORT}"
