/*
 * This file is generated by jOOQ.
 */
package me.ryang.jooq.jooq_example.tables;


import java.util.Arrays;
import java.util.List;

import me.ryang.jooq.jooq_example.Indexes;
import me.ryang.jooq.jooq_example.JooqExample;
import me.ryang.jooq.jooq_example.Keys;
import me.ryang.jooq.jooq_example.tables.records.AddressRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Address extends TableImpl<AddressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jooq_example.address</code>
     */
    public static final Address ADDRESS = new Address();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AddressRecord> getRecordType() {
        return AddressRecord.class;
    }

    /**
     * The column <code>jooq_example.address.id</code>.
     */
    public final TableField<AddressRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>jooq_example.address.people_id</code>.
     */
    public final TableField<AddressRecord, Integer> PEOPLE_ID = createField(DSL.name("people_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>jooq_example.address.street_name</code>.
     */
    public final TableField<AddressRecord, String> STREET_NAME = createField(DSL.name("street_name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>jooq_example.address.suburb</code>.
     */
    public final TableField<AddressRecord, String> SUBURB = createField(DSL.name("suburb"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>jooq_example.address.post_code</code>.
     */
    public final TableField<AddressRecord, String> POST_CODE = createField(DSL.name("post_code"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private Address(Name alias, Table<AddressRecord> aliased) {
        this(alias, aliased, null);
    }

    private Address(Name alias, Table<AddressRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>jooq_example.address</code> table reference
     */
    public Address(String alias) {
        this(DSL.name(alias), ADDRESS);
    }

    /**
     * Create an aliased <code>jooq_example.address</code> table reference
     */
    public Address(Name alias) {
        this(alias, ADDRESS);
    }

    /**
     * Create a <code>jooq_example.address</code> table reference
     */
    public Address() {
        this(DSL.name("address"), null);
    }

    public <O extends Record> Address(Table<O> child, ForeignKey<O, AddressRecord> key) {
        super(child, key, ADDRESS);
    }

    @Override
    public Schema getSchema() {
        return JooqExample.JOOQ_EXAMPLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ADDRESS_PEOPLE_ID);
    }

    @Override
    public UniqueKey<AddressRecord> getPrimaryKey() {
        return Keys.KEY_ADDRESS_PRIMARY;
    }

    @Override
    public List<UniqueKey<AddressRecord>> getKeys() {
        return Arrays.<UniqueKey<AddressRecord>>asList(Keys.KEY_ADDRESS_PRIMARY);
    }

    @Override
    public Address as(String alias) {
        return new Address(DSL.name(alias), this);
    }

    @Override
    public Address as(Name alias) {
        return new Address(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Address rename(String name) {
        return new Address(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Address rename(Name name) {
        return new Address(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
